import './globals.css'
import { SmartContractProvider } from '../../context/SmartContractContext'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={null}>
            <SmartContractProvider>
              <Navbar />
                {children}
              <Footer />
            </SmartContractProvider>
          </body>

      

    </html>
  )
}
